---
  version: '3.6'

  x-commons-depends:
    &depends-on-keycloak
    depends_on:
      - mlr-keycloak

  x-commons-secrets-java:
    &java-secrets
    secrets:
      - source: tomcat_ssl_crt
        target: /certificates/tomcat-wildcard-dev.crt
      - source: tomcat_ssl_key
        target: /certificates/tomcat-wildcard-dev.key

  x-commons-secrets-python:
    &python-secrets
    secrets:
      - source: tomcat_ssl_crt
        target: /home/python/certificates/ssl.crt
      - source: tomcat_ssl_key
        target: /home/python/certificates/ssl.key

  secrets:
    tomcat_ssl_crt:
      file: ./ssl/wildcard.crt
    tomcat_ssl_key:
      file: ./ssl/wildcard.key

  services:
    mock-s3:
      image: andrewgaul/s3proxy:latest
      container_name: mock-s3
      network_mode: "host"
      env_file:
        - ./docker/configuration/mock-s3/config.env
      hostname: s3.mock.server
      ports:
        - "8080:80"

    smtp-server:
      image: digiplant/fake-smtp:latest
      container_name: smtp-server
      network_mode: "host"
      hostname: smtp.notification.server
      volumes:
        - ./email:/var/mail

    mlr-keycloak:
      image: jboss/keycloak:10.0.0
      container_name: mlr-keycloak
      network_mode: "host"
      ports:
        - "9080:9080"
        - "9443:9443"
      #command: ["-b", "0.0.0.0", "-Djboss.socket.binding.port-offset=1000"]
      environment:
        - PROXY_ADDRESS_FORWARDING=true
        - DB_VENDOR=h2
        - KEYCLOAK_USER=admin
        - KEYCLOAK_PASSWORD=admin
      entrypoint: "/opt/jboss/tools/docker-entrypoint.sh -b 0.0.0.0 -Dkeycloak.profile.feature.upload_scripts=enabled -Djboss.socket.binding.port-offset=1000 -Djgroups.bind_addr=127.0.0.1 -Djboss.bind.address.private=0.0.0.0"
      secrets:
        - source: tomcat_ssl_crt
          target: /etc/x509/https/tls.crt
        - source: tomcat_ssl_key
          target: /etc/x509/https/tls.key
      volumes:
        - type: bind
          source: ./docker/configuration/keycloak/local_realm.json
          target: /tmp/local_realm.json
        - type: bind
          source: ./docker/configuration/keycloak/load_realm.sh
          target: /tmp/load_realm.sh
        - type: bind
          source: ./docker/configuration/keycloak/start_load_keycloak.sh
          target: /opt/jboss/startup-scripts/start_load_keycloak.sh

    mlr-legacy-db:
      image: code.chs.usgs.gov:5001/wma/docker/mlr/mlr-legacy-db:latest
      container_name: mlr-legacy-db
      network_mode: "host"
      env_file:
        - ./docker/configuration/mlr-legacy-db/config.env
        - ./docker/configuration/common/config.env
        - ./docker/secrets/mlr-legacy-db/secrets.env
        - ./docker/secrets/common/secrets.env
      ports:
        - "5432:5432"

    mlr-legacy:
      image: code.chs.usgs.gov:5001/wma/docker/mlr/mlr-legacy:latest
      container_name: mlr-legacy
      network_mode: "host"
      env_file:
        - ./docker/configuration/mlr-legacy/config.env
        - ./docker/configuration/common/config.env
        - ./docker/secrets/mlr-legacy/secrets.env
        - ./docker/secrets/common/secrets.env
      ports:
        - "6010:6010"
      << : *java-secrets
      << : *depends-on-keycloak

    mlr-notification:
      image: code.chs.usgs.gov:5001/wma/docker/mlr/mlr-notification:latest
      container_name: mlr-notification
      network_mode: "host"
      env_file:
        - ./docker/configuration/mlr-notification/config.env
        - ./docker/configuration/common/config.env
        - ./docker/secrets/mlr-notification/secrets.env
        - ./docker/secrets/common/secrets.env
      ports:
        - "6025:6025"
      << : *java-secrets
      depends_on:
        - mlr-keycloak
        - smtp-server

    mlr-legacy-transformer:
      image: code.chs.usgs.gov:5001/wma/docker/mlr/mlr-legacy-transformer:latest
      container_name: mlr-legacy-transformer
      network_mode: "host"
      env_file:
        - ./docker/configuration/mlr-legacy-transformer/config.env
        - ./docker/configuration/common/config.env
        - ./docker/secrets/mlr-legacy-transformer/secrets.env
        - ./docker/secrets/common/secrets.env
      ports:
        - "6020:6020"
      << : *python-secrets
      << : *depends-on-keycloak

    mlr-wsc-file-exporter:
      image: code.chs.usgs.gov:5001/wma/docker/mlr/mlr-wsc-file-exporter:latest
      container_name: mlr-wsc-file-exporter
      network_mode: "host"
      env_file:
        - ./docker/configuration/mlr-wsc-file-exporter/config.env
        - ./docker/configuration/common/config.env
        - ./docker/secrets/mlr-wsc-file-exporter/secrets.env
        - ./docker/secrets/common/secrets.env
      ports:
        - "6024:6024"
      << : *python-secrets
      << : *depends-on-keycloak

    mlr-validator:
      image: code.chs.usgs.gov:5001/wma/docker/mlr/mlr-validator:latest
      container_name: mlr-validator
      network_mode: "host"
      env_file:
        - ./docker/configuration/mlr-validator/config.env
        - ./docker/configuration/common/config.env
        - ./docker/secrets/mlr-validator/secrets.env
        - ./docker/secrets/common/secrets.env
      volumes:
        - type: bind
          source: ./remote-references
          target: /home/python/remote-references
      ports:
        - "6027:6027"
      << : *python-secrets
      << : *depends-on-keycloak

    mlr-ddot-ingester:
      image: code.chs.usgs.gov:5001/wma/docker/mlr/mlr-ddot-ingester:latest
      container_name: mlr-ddot-ingester
      network_mode: "host"
      env_file:
        - ./docker/configuration/mlr-ddot-ingester/config.env
        - ./docker/configuration/common/config.env
        - ./docker/secrets/mlr-ddot-ingester/secrets.env
        - ./docker/secrets/common/secrets.env
      ports:
        - "6028:6028"
      << : *python-secrets
      << : *depends-on-keycloak

    mlr-gateway:
      image: code.chs.usgs.gov:5001/wma/docker/mlr/mlr-gateway:latest
      container_name: mlr-gateway
      network_mode: "host"
      env_file:
        - ./docker/configuration/mlr-gateway/config.env
        - ./docker/configuration/common/config.env
        - ./docker/secrets/mlr-gateway/secrets.env
        - ./docker/secrets/common/secrets.env
      ports:
        - "6026:6026"
      << : *java-secrets
      << : *depends-on-keycloak
